# Generated by Django 4.2.5 on 2023-09-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_tcc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
